### ISSUE TITLE
Prepare for January 2, 2019 legacy databases shutdown.

### ISSUE THREAD

**Issue by bbkr** [bbkr/GeoIPerl6#16]
More info: https://dev.maxmind.com/geoip/legacy/geolite/

Create new module based on libmaxmind instead of libgeoip.
or
Modify this module marking `locate()` as [deprecated](https://docs.perl6.org/routine/is%20DEPRECATED) and provide complete new interface next to old one to allow easy migration.

**Comment by bbkr** [comment]
> are you going to support GeoLite2?

Yes, work is already in progress:  https://github.com/bbkr/GeoIP2.
Currently decoder can parse metadata, I'm working on locating addresses in binary trees now.

Good news is that decoder is universal for all MaxMind v2 databases, so it will open possibilities to add another databases easily, such as ISP.

> What perspectives has GeoIP::City?

It will become deprecated once GeoIP2 can provide drop-in replacement.
Traits will be added to make users aware - https://docs.perl6.org/routine/is%20DEPRECATED.
And migration instructions will be published (should be simple because GeoIP2 is PP version, libmaxminddb in system won't be required).

Module will be removed from ecosystem afer legacy databases EOL date to avoid confusion.

**Comment by bbkr** [comment]
@pheix: Please try the new https://github.com/bbkr/GeoIP2 module. I've also wrote migration tutorial [here](https://github.com/bbkr/GeoIPerl6/blob/master/Migration.md).

**Comment by bbkr** [comment]
Uh, DEPRECATED mechanism is broken big time - https://github.com/rakudo/rakudo/issues/1219.
I won't risk marking locate method as deprecated and completely crashing code for Rakudo 2018.05 users.

**Comment by m-cameron** [comment]
@pheix You should try the official library Geo::IP2Location library with the latest IP2Location LITE. You will be happy with the accuracy and query performance.

**Comment by pheix** [comment]
@m-cameron, there's no official Geo::IP2Location for Perl 6: https://www.ip2location.com/developers. I've used [Geo::IP2Location::Lite](https://github.com/leejo/geo-ip2location-lite-p6) and it's could not recognized ~25% from my test.

**Comment by pheix** [comment]
@bbkr, have been [migrated](https://gitlab.com/pheix-pool/core-perl6/commit/47eb4fb5b5c92d418ed4c7f6b4fec8288689dc06) to GeoIP2 :+1: 
Thanks for quick release!
