### ISSUE TITLE
Unhandled exception: Bytecode stream version too high

### ISSUE THREAD

**Issue by chenryn** [bbkr/GeoIPerl6#8]
MacOS

after `export DYLD_LIBRARY_PATH=/opt/local/lib`, I try to run `perl6 t/city.t`, then got such error message.

**Comment by bbkr** [comment]
Can you please link which geoip package versions you have installed (macports/macbrew)?

**Comment by chenryn** [comment]
$ port list | grep libgeoip
libgeoip                       @1.6.6          devel/libgeoip

**Comment by bbkr** [comment]
I've refactored the module to work with Perl v6.c spec and latest NC changes.

I tested it on OS X + HomeBrew and ubuntu linux.

On OS X + MacPorts exporting DYLD_LIBRARY_PATH is no longer needed.

Please try latest changes and reopen issue if it still occurs.
